version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      size-limit:
        patterns:
          - size-limit
          - '@size-limit/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
